name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn
      - run: yarn lint
      - run: yarn develop & npx wait-on http://localhost:8000 --timeout 300000
      - run: yarn storybook & npx wait-on http://localhost:6006 --timeout 300000
